vreset: -65.0 # mV
vinput: 15.0 # mV
vthresh: -50.0 # mV
eleak: -70.0 # mV
eexc: 0.0 # mV
einh: -80.0 # mV
noise: 10.0 # mV
theta_plus: 1.0 # mV
refrac_e: 10.0 # ms
refrac_i: 5.0 # ms
tme: 20.0 # ms
tmi: 10.0 # ms
te: 3.0 # ms
ti: 5.0 # ms
ttrace: 20.0 # ms
ttheta: 200.0 # ms
tdop: 200.0 # ms
lr: 3
target: 0.1
wstart: 0.9
winh: 1.0
wmax: 2.0
mu: 0.4
