vreset: -65.0 # mV
vinput: 16.0 # mV (tuned)
vthresh: -50.0 # mV
eleak: -70.0 # mV
eexc: 0.0 # mV
einh: -80.0 # mV
noise: 5.0 # mV (tuned)
theta_plus: 0.4 # mV (tuned)
refrac_e: 15.0 # ms (tuned)
refrac_i: 4.0 # ms (tuned)
tme: 20.0 # ms
tmi: 10.0 # ms
te: 3.0 # ms
ti: 5.0 # ms
ttrace: 20.0 # ms
ttheta: 470.0 # ms (tuned)
tdop: 620.0 # ms (tuned)
lr: 6 # (tuned)
target: 0.4 # (tuned)
wrandom: true # (tuned)
wstart: 0.9 # (tuned)
winh: 0.4 # (tuned)
wmax: 3.5 # (tuned)
mu: 0.1 # (tuned)
